### PR TITLE
Go import path conventions

### PR DESCRIPTION
**Pull request by drewwells**
This provides complete import path information for use by `go ....` tools. It also makes it so `source goenv` is no longer required and so people can use the library, since these changes make c6 compatible with `go get`.

### CODE REVIEW

**Comment by c9s** [comment]
I'm sorry I can't merge this PR because we have a private CI that will pull down the source from a private git repo of c6 for some tasks. this change breaks the flexibility of building c6. that's why goenv exists. :).

**Comment by c9s** [comment]
to make this package "go" getable, we need to move c6/ast to c6, so there wont be any self package import.

**Comment by drewwells** [comment]
From a modular perspective, I believe the break out to c6 and c6/ast is
better. This keeps the packages well organized and modular, easily reusable
by other packages.

Private CI should have go tools, so these changes make the code easier to
integrate with your CI since you will no longer need to manually rewrite
GOPATH and PATH environment variables. These changes are to bring the
codebase inline with what the go tools are expecting.

I'm happy to take a look at the private CI manifest, the goal is to make c6
useable with a simple `go get github.com/c9s/c6` and `go test ./...` `go
build cmd/c6 -o c6`.

**Comment by c9s** [comment]
Actually separating `c6` and `c6/ast` might cause the cyclic dependency problem in the future, so you can see I put `Context`, `Parser` under `c6`, not `c6/parser` or `c6/context`.

**Comment by drewwells** [comment]
Typically, any mutually dependent code paths are put into a separate packages. This prevents circular dependencies that are disallowed in Go. If ast and c6 need the same Types, then putting those in a 3rd packages resolves any circular dependencies.

Also, the wercker build is very troublesome ><

**Comment by c9s** [comment]
I would still prefer describing the instruction of building the binaries in the readme file. If people want to try the bleeding edge stuff, then go ahead for the instructions.     For users, we will have pre-built binaries, for them to download. But changing the import path is not in the plan, I agree you we should use the import path like this when writing go libraries,  but c6 is an application, it's not something everyone will import in their code.

**Comment by drewwells** [comment]
The intention of these changes is to make c6 usable with the standard go tools.

If there's no desire to make this library work with `go`, then no point in me trying to address that! The standard go tools will never run make files or custom scripts, so leaving leaving the library as is will make it incompatible with any go tools.

**Comment by c9s** [comment]
what kind of the go tool you want to use over c6 (except the go get)?

**Comment by drewwells** [comment]
I'd expect `go get github.com/c9s/c6` to work without errors. Also once in the source folder `go test ./...` should run all tests without errors.

This is all for selfish reasons, I would want to import `github.com/c9s/c6` so that I can use c6's compiler engine. So far from this commit, I would be able to import `github.com/c9s/c6/src/c6` and get all the power of c6.

I understand you are just trying to get your application going. So I wanted to help out by making these few minor changes to make your work easily integrated  by other open source projects. I'm happy to hash this out further on Slack as well :)

**Comment by c9s** [comment]
HI @drewwells,

I can make c6 available to you to `import github.com/c9s/c6` in your engine, however the `go get` command provided by golang team doesn't handle the package dependency very well.

If any dependent package API changed on master, everything will be broken when user runs `go get`.  Therefore we control the package dependency we used by using `goenv`: install packages on specific tag or branch. This is to prevent unexpected results while we need to build stable application for users.

The package depedency management was denoted in #6, but we didn't found a good enough package manager for this..... yet.   so `goenv` is a quick solution, and it works for everything.

One solution for you to integrate into the engine you used for now is, merging c6/ast into c6, that way we won't have self import (e.g. `import c6....`) breaking the build.

And the command packages will be left in `c6/cmds` as it is.

**Comment by drewwells** [comment]
Go's package manager does not provide a lot of flexibility. However, there are many ways around this `makefile` [godep](https://github.com/tools/godep) [gb](getgb.io/docs/install/).For c6, you have very few dependencies. In fact, the one you are mentioning `c6/ast` which is in the repo itself so git is already managing dependencies for you.

However, the changes I'm recommending have nothing to do with package management. These changes provide complete import paths so Go can build the project. As it stands, the project can not be built and will not be very useful to people. Maybe this example helps

import "c6" -> import "github.com/c9s/c6/src/c6"
import "c6/ast" -> "github.com/c9s/c6/src/c6/ast"
import "c6/symtable" -> import "github.com/c9s/c6/src/c6/symtable"

These changes are based off the Go docs here: https://golang.org/cmd/go/#hdr-Remote_import_paths

**Comment by c9s** [comment]
Yes I understand. but I don't want to make this package depends on the import path `github.com/c9s/c6/...`.  

As mentioned above, we have a private repository that will be used for a private CI environment, changing this makes it hard to work privately.

**Comment by c9s** [comment]
Hi @drewwells 

I know this makes people unhappy, the only solution is to merge c6/ast into c6, that will make the package works for you.

And I really don't want to make people feel disappointed, please open a discussion issue and we can discuss there before you put a lot efforts on the PR.

Thank you for your understanding.

**Comment by c9s** [comment]
@drewwells , the installation instruction is described here: 03b0435

**Comment by drewwells** [comment]
gb is a go build tool chain that moves away from go path https://github.com/constabulary/gb/issues/133

**Comment by c9s** [comment]
yeah, I've surveyed it few weeks ago, it seems good, but unfortunately it's not mature/stable enough.

**Comment by c9s** [comment]
This shall be fixed when the import comment is ready. (it's now in the go internal code, but it's not landed into the language spec documentation)

https://docs.google.com/document/d/1jVFkZTcYbNLaTxXD9OcGfn7vYv5hWtPx9--lTx1gPMs/edit

**Pull request closed without merging**
