### PR TITLE
Go vet. Remove deadcode from lexer.

### PR DESCRIPTION
**Pull request by omeid**
Please check the deadcode parts commented out with `XXX`. They same to indicate likely bugs.

I have also changed `Lexer.error` to `Lexer.errorf` as that is the convention for methods that takes a formatting string.

I have also fixed the issue where the wrong verb (`%s` string) was used for `runes`.

### CODE REVIEW

**Comment by c9s** [comment]
looks like the travis-ci tests are falling because the typewriter package, I think we can remove it: `c6/typewriter/symtable`

**Comment by omeid** [comment]
@c9s What is it used for? if not needed no more, you can remove it and I will trigger the CI again.

**Comment by c9s** [comment]
the typewriter package was created for gen. however we don't use it anymore. I can't modify your PR, maybe you can simply rm the directory and push again.

**Comment by omeid** [comment]
I did, but you could just remove it from the master and it would have reflected. Git magic. :)

**Comment by c9s** [comment]
done. please rebase this PR from master. :)

**Comment by c9s** [comment]
Great! it works now

**Pull request merged**
