### PR TITLE
Make c6 Go Get-able, Format, prepare for linting.

### PR DESCRIPTION
**Pull request by omeid**
Great work, but I don't see no reason to break compatibility with go tools, if anyone wants to have reproducible builds, they can use [GoDeps](https://github.com/tools/godep).

I also passed all the code through `go fmt` and have added golint to Makefile, there is a tones of issues that needs to be fixed.

Once this is merged in, I am happy to help with linting the code and implementing missing features.

### CODE REVIEW

**Comment by c9s** [comment]
how do i make it work with the private repository by this PR?

**Comment by c9s** [comment]
I like the golint  support, however can we separate ths support in another PR?

**Comment by omeid** [comment]
@c9s Can you please clarify what do you mean by making it work with your private repository? 

In a simple scenario, you would just clone this code into your "private" `GOPATH/github.com/c9s/c6`.

if you want to use it with another project and want reproducible builds, you would just import it with `github.com/c9s/c6` path and once you call `godep save` it will simply clone the code and fix all the paths for you, automagically.

**Comment by omeid** [comment]
@c9s Yes, sure. I can revert the "golint"/go vet part. 
So first `go get-able`/restructuring, then golint/go vet in another pull request?

**Comment by omeid** [comment]
`godep` is working to work along with Go 1.5's official [vendoring](https://github.com/golang/go/commit/183cc0cd41f06f83cb7a2490a499e3f9101befff) experiment. So this seems to be the _official_ way forward.

**Comment by c9s** [comment]
Here is our development cycle:

1. Push unstable changes to private repository. for example revision A.
2. Jenkins fetch the private repository (not the github one) and build the package with dependency
3. Ship compiled binaries for different platform (nightly builds)
4. Once we got stable version, push changes to GitHub

However I am not opposed to go get-table, I just wish that the build instructions can be the same, so we don't have to maintain the scripts and make it works fluently on both Jenkins and Travis-CI.

It would be great if you are willing to provide a godep PR for the above requirement before go-getable (?), then I think we can merge the go-getable PR.

And... If we can merge the golint PR before any things described above and that would be great too.

# golint PR
# godep for better build instructions
# go getable

Thanks for your contributions. :+1:

**Comment by omeid** [comment]
@c9s The remote location doesn't matter.

1. Push code to `private/repo/c6`
2. Jenkis fetches the revesion A from `private/c9s` to `$GOPATH/github.com/c9s/c6`
3. Build and Ship.
4. Push to `github.com/c9s/c6`

Go tools are only interested in the location of the repository in the file system, regardless of it's `origin`.

**Comment by omeid** [comment]
Nothing needs to be done for `godep`, it will just work fine with anything that is `go get-able`.

**Comment by omeid** [comment]
@c9s Is there any reason there is both Travis and Wercker?

**Comment by c9s** [comment]
you can basically ignore wercker, it was used when travis ci didnt work

**Comment by omeid** [comment]
So travis is now happy, sort of.

Here is my suggested path:

1. Restructure and make it go get-able.
2. Format code according to `go fmt`.
3. Go vet.
4. Start linting one package at a time.

**Comment by c9s** [comment]
It seems that coveralls is not working, can you take a look?

**Comment by omeid** [comment]
It is working, but `compiler` package which wasn't excluded has very low coverage, it has resulted for the over all coverage to decrease.

**Comment by omeid** [comment]
@c9s Good idea, while we are at it, the tests should only need `go test`, that is, you should not require any other steps to run the tests and for them to pass.

The makefile should be just used for development, but do you really need the `gen`? I couldn't figure out what it is exactly used for? is it possible to drop it?

**Comment by c9s** [comment]
No, we aren't using the `gen`, I removed it because it's using Go 1.4 API.

**Comment by omeid** [comment]
@c9s So with no `gen` there is almost no reason to have a `Makefile`. I will update the travis and documentation accordingly.

**Comment by omeid** [comment]
@c9s Also, can you please disable either Travis or Wrecker please.

**Comment by c9s** [comment]
Thanks, I've removed the Wrecker webhook

**Pull request merged**
